[package]
name = "runner"
version = "0.1.0"
edition = "2024"

[dependencies]
cpuutils = { path = "../cpuutils" }
config = { path = "../config" }
sysinfo = "0.36.1"
thiserror = { workspace = true }
clap = { workspace = true, features = ["derive"] }
