[package]
name = "fuse"
version = "0.1.0"
edition = "2024"

[dependencies]
fuser = "0.16.0"
config = { path = "../config" }
thiserror = { workspace = true }
libc = { workspace = true }
home = { workspace = true }
tracing = { workspace = true }
runner = { version = "0.1.0", path = "../runner" }
